DROP DATABASE IF EXISTS test1;
CREATE DATABASE test1;
GRANT ALL PRIVILEGES ON test1.* TO 'test1'@'localhost' IDENTIFIED BY 'test1';
GRANT ALL PRIVILEGES ON test1.* TO 'test1'@'%' IDENTIFIED BY 'test1';
USE test1;
